baseurl = "https://TribeWorks.software/"
languageCode = "en-us"
title = "TribeWorks: A Teal Software Development Organization"
theme = "hugo-material-banner"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	# author = "Bruce Eckel"
	description = "A Teal Software Development Organization"

	logo = "/images/tribeworks-circle-web.png"
	favicon = "images/tribeworks-favicon-96.ico"
	banner_image = "/images/TribeWorksBanner.png"

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

  [params.palette]
  	primary = "teal"
  	accent  = "red"

  [params.font]
  	text = "Ubuntu"
  	code = "Ubuntu Mono"

[social]
	twitter = ""
	github  = "TribeWorks/TribeWorks-hugo"
	email   = "mindviewinc@gmail.com"

[[menu.main]]
	name   = "Overview"
	url    = "overview/"
	weight = 10

[[menu.main]]
	name   = "How We Work"
	url    = "how/"
	weight = 20

[[menu.main]]
	name   = "People"
	url    = "people/"
	weight = 25

[[menu.main]]
	name   = "Process"
	url    = "process/"
	weight = 30

[[menu.main]]
	name   = "Technologies"
	url    = "technologies/"
	weight = 40

[[menu.main]]
	name   = "Contact"
	url    = "contact/"
	weight = 50

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
